
export const apiUrl = {
    //BASE_URL: "http://localhost:5000",//"https://click-jewelry-api.herokuapp.com",
    version: '/v1.0',
    apiPath: '/api',
    userDataUrl: '/auth/get-user-access',
    categoriesPath: '/store/categories',
    caratsPath: '/store/carats',
    metalsPath: '/store/metals',
    rattiMethodPath: '/store/ratti-methods',
    productCodePath: '/store/generate-product-code',
    productPath: '/store/product',
    productByCodePath: '/store/product/by/code',
    productsPath: '/products',
    customersPath: '/store/customers',
    customerPath: '/store/customer',
    salesmenPath: '/store/salesmen',
    salesmanPath: '/store/salesman',
    goldApiPath: '/gold',
    suppliersPath: '/suppliers',
    countersPath: '/hens/find',
    counterPath: '/hens/new',
    categoriesPath: '/categories/find',
    categoryPath: '/categories/new',
}
